### ISSUE TITLE
Tray app icon is not visible in macos light mode

### ISSUE THREAD

**Issue by balupton** [textileio/desktop#19]
![Screen Shot 2019-04-17 at 3 58 07 pm](https://user-images.githubusercontent.com/61148/56663118-a9e03600-66e8-11e9-9d1f-621822c175b2.png)

Also being reported on the slack by users:

- https://textile-public.slack.com/archives/C4R0Z1U5Q/p1556105651001500

Could also be the cause of this user's trouble here:

- https://textile-public.slack.com/archives/C4R0Z1U5Q/p1556075149091400

**Comment by andrewxhill** [comment]
assigning this one to you @carsonfarmer since you're a bit more familiar with that icon setting

**Comment by carsonfarmer** [comment]
Oh yeh. The white icon is hard coded at the moment. Thanks for the ticket 👍

**Comment by carsonfarmer** [comment]
Fixed with #29
