### ISSUE TITLE
invalid account address encountered (invalid version byte), skipping

### ISSUE THREAD

**Issue by sanderpick** [textileio/desktop#20]
`ERRO[0003] invalid account address encountered (invalid version byte), skipping` when repo dir contains non-account parse-able folders.

tnx @obo20 for the report!

**Comment by carsonfarmer** [comment]
Ah thanks for the report. This error is safely ignored (‘skipping’), so should probably just be made into a warning. Unless you think we should just not report at all?

**Comment by carsonfarmer** [comment]
Fixed to produce a warning instead with #29
