### ISSUE TITLE
How to build a React app using the Textile tray

### ISSUE THREAD

**Issue by andrewxhill** [textileio/desktop#22]

**Comment by carsonfarmer** [comment]
What about this one Andrew?
https://medium.com/textileio/introducing-the-textile-desktop-series-f9eb14e1349e

**Comment by andrewxhill** [comment]
great! but it could be lost in time there.

i'm on the fence about what the right section is in docs right now. Tutorials seem like they might need their own home entirely. `Recipes` could be very interesting to start putting a library together on the docs site. In which case, the above post could be broken into a few recipes with some yaml'fied code we can maintain.
