### ISSUE TITLE
Cafes don't show when creating a Textile wallet

### ISSUE THREAD

**Issue by leshokunin** [textileio/desktop#24]
![Example](https://i.imgur.com/LpFAS5cl.png)
Using Textile_v0.1.12-rc1_windows-amd64

**Comment by carsonfarmer** [comment]
@sanderpick and @leshokunin do either of you have an opinion here? Should we leave this as 'wontfix', add defaut cafes option (do we have any) or what?

**Comment by leshokunin** [comment]
So it depends on what cafes are for. I've always assumed my saved data was going to a default cafe when I write something. If so, it should be clear what cafe we're using. I also think populating the list with a default cafe would help.

I think Lily has been looking at a "select cafe" feature for Epona too, but this might be the better option actually.

**Comment by carsonfarmer** [comment]
For apps (like Epona) wanting to supply their own Cafes, if you add the Cafe from your app, it should automatically show up in this list. So if you wanted, you could a) check that there are existing Cafes (there aren't any by default), and if none, b) ask to add the Epona cafe. Then, it'll be there ready for them.

**Comment by leshokunin** [comment]
I think it'd be nice to populate with some default known ones. Like when I
use Mirc, it shows there's Freenode and others.
