### ISSUE TITLE
Error when trying to edit config file

### ISSUE THREAD

**Issue by leshokunin** [textileio/desktop#25]
![Example](https://i.imgur.com/v5Qw9Oe.png)
Using Textile_v0.1.12-rc1_windows-amd64

**Comment by carsonfarmer** [comment]
Actually, this is because we're storing data in a non-standard path on windows. Might be worth changing this to the default locations used by electron apps.

**Comment by carsonfarmer** [comment]
Should be fixed with #30. Once the new release comes out, if this is still an issue, please reopen.
