### ISSUE TITLE
Before initial sync accessing threads makes height of dropdown 1px

### ISSUE THREAD

**Issue by Gozala** [textileio/desktop#39]
I assume this happens because threads have not fully synced yet (as later on they seem to work fine) but once I sign in into new account, and click threads tab dropdown turns into a approximately 1px line and there is no way to do anything from that point on other than quit a textile process and start over.

**Comment by carsonfarmer** [comment]
Oops, yes this is likely exactly what is going on here. Nice catch. Should be an easy check, catch, and hopefully fix.
