### ISSUE TITLE
App quits after account creation

### ISSUE THREAD

**Issue by jehunter5811** [textileio/desktop#41]
Steps to reproduce: 

-On MacOS, launch the tray app
-Create new account
-Protect with password
-After protecting with password, app quits (at least for me)

**Comment by sanderpick** [comment]
Thanks! Related: https://github.com/textileio/go-textile/issues/809

**Comment by carsonfarmer** [comment]
But _without_ a password, creating a new account does _not_ crash the app?

**Comment by jehunter5811** [comment]
That is correct. It works as expected when not using a password.

**Comment by carsonfarmer** [comment]
After some remote debugging with @jehunter5811, we discovered that this is an issue with password handling. If passwords have `'` or possibly spaces in them, this seems to cause issues. This is a bug, and should be fixed ASAP.

**Comment by carsonfarmer** [comment]
Fixed with https://github.com/textileio/go-textile/pull/815
