### ISSUE TITLE
Enable/scope Bluetooth connection

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/desktop#60]
We need to enable Bluetooth pairing on desktop _and_ mobile. Here's a great/useful example: https://github.com/aalhaimi/electron-web-bluetooth

**Comment by carsonfarmer** [comment]
Requires parallel work on mobile, currently tracked as part of a larger RFC here: https://github.com/textileio/photos/issues/1302

**Comment by doodlemania2** [comment]
Wouldn't the QR code approach be easier? I don't know of too many people that have bluetooth enabled on their PCs for that type of setup.
