### ISSUE TITLE
Cafe session mgmt

### ISSUE THREAD

**Issue by andrewxhill** [textileio/desktop#8]
Seems like the architecture now means that we should do token/session mgmt directly in the desktop app as primary (maybe which can be overwritten by and developer app). 

thinking through it for the pages app, it'd be nice just to let the main.go handle grabbing the session and then let pages.go use that session for remote pin requests.

**Comment by andrewxhill** [comment]
let me know if that jives with your thinking @carsonfarmer

**Comment by sanderpick** [comment]
Hmm, this doesn't sound right @andrewxhill. Remote pins are handled by the cafe request queue, which, on desktop, is all handled internal to the lib.

**Comment by andrewxhill** [comment]
ah sure, okay nice. head in mobile land
