### ISSUE TITLE
bash\r issue when running on linux

### ISSUE THREAD

**Issue by Diomas** [textileio/desktop#9]
Hi,

when I'm trying to run the app using `yarn dist -o linux && go run *.go`, i'm getting this:

```
$ yarn dist -o linux && go run *.go
yarn run v1.12.3
$ yarn build
$ craco build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  801.31 KB  build/static/js/2.df34d41c.chunk.js
  97.27 KB   build/static/css/2.0b789891.chunk.css
  8.44 KB    build/static/js/main.826b661f.chunk.js
  764 B      build/static/js/runtime~main.8c97409f.js
  399 B      build/static/css/main.18303bca.chunk.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://bit.ly/CRA-deploy

$ rimraf resources & move-cli build resources
$ ./scripts/bundle.sh -o linux
/usr/bin/env: ‘bash\r’: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by carsonfarmer** [comment]
Thanks for the bug report. This _seems_ like a line-endings issue? But the file is LF, so this is surprising? Could you please try running the code found in bundle.sh directly to help rule out any other sources of error?

```
yarn install
yarn build
go get github.com/asticode/go-astilectron-bundler/...
go install github.com/asticode/go-astilectron-bundler/astilectron-bundler
astilectron-bundler -v -c bundler.linux.json
```

**Comment by Diomas** [comment]
Thank you for reply! Changing first line to simply `#!/bin/bash` worked for me

Also I've faced errors on this missed packages:
"github.com/asticode/go-astilectron-bootstrap"
"github.com/golang/protobuf/jsonpb"
"github.com/ipfs/go-ipfs/repo/fsrepo"
"github.com/textileio/go-textile/core"
"github.com/textileio/go-textile/gateway"
"github.com/textileio/go-textile/keypair"
"github.com/textileio/go-textile/pb"
"github.com/textileio/go-textile/wallet"

wouldn't it be better to have them listed somewhere in readme or maybe as `go get` instructions in this bundle.sh?

**Comment by Diomas** [comment]
Appears bundle.sh need to be fixed anyway because of wrong line endings

I've got mine work not because of changes but because I was made it a new file from scratch

Existing bundle.sh can be fixed with `sed -i -e 's/\r$//' scripts/bundle.sh`

**Comment by carsonfarmer** [comment]
Those packages should be automatically fetched, as we are using go modules. You should not have to install them separately. I will see about adding a go build step to prefetch these packages during build.

**Comment by carsonfarmer** [comment]
Yes I suspected it was a line endings issue. Though surprised this cropped up. Must be a git thing? In any case, thanks for the report and suggested fix 👍

**Comment by balupton** [comment]
https://github.com/textileio/meta/issues/3 should solve this, as it enforces lines endings

**Comment by carsonfarmer** [comment]
Just digging into this issue again. The line endings are unix style already AFAIK? The shebang fix is a good one, but [according to reddit](https://www.reddit.com/r/linuxadmin/comments/975nok/binbash_vs_usrbinenv_bash/) `#!/usr/bin/env` is pretty good practice in terms of portability. I'm going to close this as 'wontfix', but please do reopen if you think this needs more care!

**Comment by balupton** [comment]
@carsonfarmer this was probably fixed this earlier when the editorconfig and prettier changes landed in go-textile a few weeks ago, hence why looking at it now is only unix line endings, so probably is a fixed rather than wontfix

**Comment by carsonfarmer** [comment]
I don’t think that fix would have any affect on this repo though?
